#left after .net core api needs to be redesigned to spring api
version: "3"
services:
    api:
        env_file: 
            - .env
        build: ./src/Backend/Api/SpeakNative/.
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker