version: "3"
services:
    db:
        env_file:
            - .env
        build: ./src/Backend/DB/Deploy/.
        ports:
            - "1433:1433" 
        environment:
            - "ACCEPT_EULA=Y"
            - "MSSQL_PID=DEVELOPER"
          